eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082


spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      routes:
        - id: informacoesCadastrais
          uri: lb://INFORMACOES-CADASTRAIS
          predicates:
            - Path=/teste/**
        - id: serverauth
          uri: lb://SERVER-AUTH
          predicates:
             - Path=/oauth/**



