eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082


spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: serverAuth
          uri: lb://SERVER-AUTH
          predicates:
            - Path=/oauth/**,/user/**
        - id: informacoesCadastrais
          uri: lb://INFORMACOES-CADASTRAIS
          predicates:
            - Path=/pedido/**,/fornecedor/**
        - id: servicoCliente
          uri: lb://SERVICO-CLIENTE
          predicates:
            - Path=/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

